### ISSUE TITLE
Integration of SwE results with pTFCE

### ISSUE THREAD

**Issue by BryanGuillaume** [NISOx-BDI/SwE-toolbox#118]
A user seemed very interested to use the toolbox pTFCE with the results obtained through the SwE toolbox. @nicholst, as you are one of the co-authors of the related paper, can you tell me if there would be any issues with this?

**Comment by nicholst** [comment]
pTFCE depends on parametric RFT and as a result is not suitable for use with the SwE. Sorry!

**Comment by BryanGuillaume** [comment]
Thanks for this important information. I will therefore close this issue as this integration is not suitable.
