### ISSUE TITLE
The FDR-corrected p-values on the WB display seem wrong

### ISSUE THREAD

**Issue by BryanGuillaume** [NISOx-BDI/SwE-toolbox#124]
When I look at the WB result display, the FDR-corrected p-values looks all the same, which is suspicious (see the 2 examples below). Also, If I control for the a FDR of 5% (see second example below), the surviving voxels have higher FDR p-values than 5%, which is not possible.

<img width="595" alt="Screenshot 2019-06-11 at 14 16 15" src="https://user-images.githubusercontent.com/4426961/59275079-ebf31600-8c5b-11e9-9873-b07d9d90bed7.png">
<img width="639" alt="Screenshot 2019-06-11 at 15 16 12" src="https://user-images.githubusercontent.com/4426961/59275115-ff9e7c80-8c5b-11e9-8d75-c54656ba23a5.png">

**Comment by BryanGuillaume** [comment]
I think this is not a bug per se. The issue is that some displayed p-values are based on the **WB** while some others are based on the **parametric test**. In particular, for the FDR inference, the **threshold** seems to be done on the FDR corrected p-values computed from **parametric uncorrected p-values** while the **display** shows the FDR p-values  computed from the **WB uncorrected p-values**. This choice between parametric and non-parametric p-values seems sometimes arbitrary and thus confusing for the display of WB results. 

I believe that it would be great to be improve this by clearly specifying which p-values should be  thresholded (we could offer both type) and which p-values are displayed (we could display both parametric and non-parametric results). 

@nicholst, what is your opinion about this?

**Comment by nicholst** [comment]
I do recall discussing thresholding issues with @TomMaullin.  The question
was what image to base thresholding on and which image to show in the SPM
MIP display.  If I recall, we opted to show the statistic image (i.e. just
the F or T), and thus may have opted for a threshold based on *parametric*
uncorrected p-values (which, while not exactly 1-1 with F & T values, are
more related than the *nonparametric* uncorrected p-values).

I just checked and, for reference, SnPM bases its FDR p-values on
nonparametric uncorrected p-values.

While I would like to be consistent, and go uniformly with nonparametric
inferences, without having some experience with the difference between FDR
based on parametric vs nonparametric uncorrected p-values, I'm worried
about committing one-way or another.

So!  Can we make it an option?  I don't want to make it too easy (to
discourage fishing), so what about:  We add an option to the Batch
interface

FDR inference...

from parametric p-values

from nonparametric p-values


And... as for the default?... I guess let's start with 'from nonparametric
p-values', but if that gives weird results we can switch it later.

Does this sound good?

**Comment by BryanGuillaume** [comment]
I agree with the FDR inference thresholding option in the batch. That avoids fishing for a result and make clear what is in use later in the display of results. For the display of the FDR-corrected p-value in the table, what do we do? Do we follow the thresholding option?

In a side note, the weird results in the image above for the FDR corrected p-values based on non-parametric p-values (i.e the identical FDR-corrected p-values) are clearly due to the small number of bootstraps.

**Comment by nicholst** [comment]
Let's wait to move forward on this until we have a master table of all
possible thresholding options (threshold action, and image upon which the
threshold is based).

**Comment by BryanGuillaume** [comment]
This issue has been handled in PR #131. Now, when a model uses a WB procedure, all the p-values displayed are WB p-values.
