### ISSUE TITLE
Detailed comment review is needed

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#14]
Just noticed that `swe_getSPM.m`'s references ess images, which I'm pretty sure are not written out.  All of the documentation in the file headers needs to be reviewed, especially the ones essentially directly imported from SPM.

**Comment by nicholst** [comment]
To clarify, this refers to the header comments in each file, not detailed comment review of each line.

**Comment by TomMaullin** [comment]
This has now been addressed by PR #43
