### ISSUE TITLE
Change CIFTI output naming to match PALM

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#148]
PALM uses 'dpx' instead of 'vox' for the filename type when reading CIFTI; change to match PALM.

**Comment by BryanGuillaume** [comment]
I agree that `vox` might no be appropriate for CIFTI outputs. However, I am not sure that `dpx` was really intended for CIFTI data as it seems to stands for "surface-data without specification" 

Indeed, from PALM documentation,

> This can be `vox` for voxelwise, `vtx` for vertexwise, `fac` for facewise, `dpx` for surface-data without specification (it can be vertexwise or facewise if the actual surface geometry wasn't supplied with the -s option), `dat` for any data that doesn't necessarily have a spatial meaning

As CIFTI can contain both surface and volume data, that does not seem a perfect naming. If I were to pick something from the list, I would use `dat`, but this is quite a subjective choice.

Anyway, if the only goal is to match PALM as best as we can, I can change it to `dpx`. On this note, I should also change output naming for GIFTI data, but I am not too sure how to detect if the data is vertexwise or facewise. Maybe, I should use `dpx` per default for GIFTI and CIFTI data.

**Comment by nicholst** [comment]
I agree `dpx` doesn't really seem perfect, but at this point I'm happy to just go along with the PALM convention. (And then we don't have to worry about whether area has been considered, or whether voxels have also been considered.)

**Comment by nicholst** [comment]
@BryanGuillaume I guess this can be closed now?

**Comment by BryanGuillaume** [comment]
Yes, this has been handled in PR #151. Thus, I am closing this issue.
