### ISSUE TITLE
Add warning when intercept is not in the model

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#16]
While not strictly a "bug", a model with no intercept is such a catastrophic modelling decision it basically is one.

@TomMaullin - Let's discuss how to add this ASAP.

**Comment by nicholst** [comment]
A simple check would be 
```matlab
all(one(N,1)==P*ones(N,1))
```
but probably should be done as an `abs(diff)>sqrt(eps)` to allow imperfect numerical precision.

**Comment by TomMaullin** [comment]
This issue has been addressed by PR #30
