### ISSUE TITLE
Problem with toolbox

### ISSUE THREAD

**Issue by JohnAshburner** [NISOx-BDI/SwE-toolbox#17]
![fig1matrix](https://user-images.githubusercontent.com/11646203/40376792-2eebc10e-5de7-11e8-95bc-cfee47c705c2.jpg)
![fig2](https://user-images.githubusercontent.com/11646203/40376797-34124342-5de7-11e8-9cce-6094ebd29d33.jpg)

A question that was passed on to me:

> Dear John,
>  
> I hope you’re well. I’m a UCL student working on longitudinal neuroimaging (we’ve been in touch about this before), and I’m writing up my thesis at the moment. I’m looking to seek some advice from you about the conundrum I’m facing (described below). I’ve posted this twice on the SPM mailing list, but to no avail.
>  
> Do you have any insight about it, or do you know anyone who might be able to help me with it? I’ve tried Ged Ridgway, who helped me out with Sandwich estimation last year on another project, but haven’t heard anything back.
>  
> I’d appreciate any help you might be able to give
>  
> Thanks
>  
> 
> From: XXX, XXX 
> Sent: 21 May 2018 11:52
> To: SPM@JISCMAIL.AC.UK
> Subject: Longitudinal image analysis using Sandwich estimation with small numbers
>  
> Dear all,
>  
> This is a question for those of you who use the Sandwich Estimator (SwE), to model longitudinally registered images. Or any general imaging stats experts who are familiar with SwE, and marginal models.
>  
> My model is looking at change in voxel volume predicted by diagnostic group (of which there are 5), presence of a cerebral microbleed (MB) (binary covariate interacted with diagnostic group) and other covariates (see design matrix fig 1).
>  
> The issue I am having is that one of my groups (SMC) has a very low number of individuals with a microbleed (only 6 out of 70). Therefore, the contrast investigating MB associations in this group looks very odd, with huge z scores (see fig 2 attached).
>  
> I have found results for the effect of MB on atrophy rates in other groups in the same model. My question is whether these results are invalidated the strange effects in SMC. As there is an interaction, the issue is only in the SMC group; would the fact it has not coped well with small numbers in this group interfere with the statistical relationships of covariates on atrophy rates in any other group?
>  
> One sanity check I could perform is to run the model without the SMC group, to see if the results in other groups change.
>  
> Let me know if you have any contributions to this.
>  
> Many thanks in advance
>

**Comment by nicholst** [comment]
Thank you @JohnAshburner!  Sorry I missed this.  I've replied on the list.
