### ISSUE TITLE
Model configuration display - disable latex interpreter

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#18]
For the reporting of the design, the columns of the design matrix are show with their names, but with `interpreter` set to `latex`, which creates names like "`Grp_AD`" to be rendered "Grp<sub>A</sub>D".

Change the interpreter to `none` for this figure to solve this.

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I've been looking into this and believe that this happens inside `spm_DesRep.m` (see [line 1018](https://github.com/neurodebian/spm12/blob/master/spm_DesRep.m#L1018)) and not an `SwE` function - If I've understood correctly I think this may be the normal SPM behaviour. However, if you like, I could create an `SwE`-equivalent version of the file, i.e. `swe_DesRep.m`, with just the interpreter changed, but am not sure if there might be an easier way of doing this... do you have any know of any easier ways to change the interpreter without duplicating the SPM code?

**Comment by nicholst** [comment]
Thanks for tracking this down!

Let’s make a swe_DesRep and send it to Guillaume & suggest he likewise
updates spm_DesRep.
-- 
_________________________________________________________
Thomas Nichols, PhD
Professor of Neuroimaging Statistics
Nuffield Department of Population Health | University of Oxford
Big Data Institute | Li Ka Shing Centre for Health Information and Discovery
Old Road Campus | Headington | Oxford | OX3 7LF | United Kingdom
T: +44 1865 743590 | E: thomas.nichols@bdi.ox.ac.uk
W: http://nisox.org | http://www.bdi.ox.ac.uk

**Comment by TomMaullin** [comment]
This has been addressed by PR #37
