### ISSUE TITLE
Display "whole brain" p-values right away.

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#28]
For a period of time, SPM *did* *not* show any table of p-values until you clicked on a button under "p-values", and SwE mimics this behaviour.  

This behaviour in SPM has now changed, and users are presented with the "whole brain" results right away.

@TomMaullin - Can this behaviour please be added to SwE, parametric & WB?  I.e. after "Results" finishes, instead of a blank lower half, you should see the "whole brain" p-value table.

**Comment by TomMaullin** [comment]
This issue has been addressed in PR #23.
