### ISSUE TITLE
Remove fig-based GUI window - Adopt Batch-only system

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#29]
I like having a main 'GUI' for SwE (miss it in SnPM), but ultimately we want to be fully grounded in the Batch System so as to facilitate scripting.

However, even if we keep a GUI (that just opens up batch jobs), we  should get rid of this `swe_ui_main.fig` ... it is only editable via Matlab GUI editor, GUIDE.  While font sizes are tweaked in  `swe_ui_main.m` I'd rather just have a figure created from scratch each time.  Also, I have done some tests and found that the GUI based on `swe_ui_main.fig` is *very* slow on first click; I thought this was due to delays with the batch system firing up, but I don't think this the explaination.

**Comment by TomMaullin** [comment]
Hi @nicholst ,

Just to clarify, if keeping the main GUI, is there a preferred editor you would like to build it from? Or would you prefer the GUI be built from scratch through the `uicontrol` functions?

**Comment by nicholst** [comment]
Build from scratch.  Sounds like a pain, but we have templates (SPM or
SnPM) that we can clone.

**Comment by TomMaullin** [comment]
Ah okay! No that's fine! Did you have any in particular SPM/SnPM menus in mind which you wanted the GUI to resemble?

**Comment by TomMaullin** [comment]
Currently, the options are 'Specify Model', 'Run Model' and 'Results'.

**Comment by nicholst** [comment]
Oh, right... then those are the 3 buttons we need!  I just realised that the oldest SnPM on GitHub has now GUI window.

Please look here: https://gist.github.com/nicholst/4eb26c999fd736b8ebc063fb4543272f

Around Line 92 is the start of the creation of the window.

**Comment by TomMaullin** [comment]
This issue has been resolved by PR #46
