### ISSUE TITLE
Provide a better way to extract information for WB analyses

### ISSUE THREAD

**Issue by BryanGuillaume** [NISOx-BDI/SwE-toolbox#4]

**Comment by jonkoller** [comment]
Some additional input:

For the "lP_clusterFWE" images, maybe provide a text file with the list of clusters with some statistics (size, p-value, center of mass, etc.)

**Comment by nicholst** [comment]
Thanks @jonkoller !  We're currently looking at ways to make it easier to extract the SwE results and view them in a generic SPM-like viewer tool. (w/ @cmaumet, @TomMaullin & co).  I'll update this issue when we have more info.

**Comment by nicholst** [comment]
This feature request was echo'd by Mary Heitzeg's group at the University of Michigan; extraction of values is really important.

**Comment by copelora** [comment]
We've been using fsl cluster to produce a results table from the WB, but with no luck. We've tried the various lP_* files, but we get zero results, despite being able to view the clusters with SPM display. What might we be doing wrong? Any update on the "easier" way of going about getting a results table?

**Comment by nicholst** [comment]
That's for the feedback!

So, to be clear, when *not* using the Wild Bootstrap method you get results, but using the WB method you don't get anything sensible from the lP* images?  Can you send me some example *lP* files that don't seem to make sense?  You can upload big files here: https://oxfile.ox.ac.uk/oxfile/work/extBox?id=489046F8D241F037E8

**Comment by copelora** [comment]
That's correct. With the non-WB results, I used an spmZ, which gave the results I expected. With any of the WB lP* images, I get only the fsl cluster column headings but no results (but viewing the same files in SPM display shows that there are results).

**Comment by nicholst** [comment]
@copelora: I’ve found the problem… SwE masks all output images implicitly with NaN, and FSL *hates* NaN’s :)

So if you do the following you’ll be all set:

fslmaths lP+ -nan lP+_nan
fslmaths lP_FWE- -nan lP_FWE-_nan
fslmaths lP_clusterFWE+ -nan lP_clusterFWE+_nan

… and then cluster will work:

$FSLDIR/bin/cluster -i lP_clusterFWE+_nan -t $(echo "-l(0.05)/l(10)"|bc -l)
Cluster Index	Voxels	MAX	MAX X (vox)	MAX Y (vox)	MAX Z (vox)	COG X (vox)	COG Y (vox)	COG Z (vox)
6	15522	3	14	34	9	39.1	22.6	28.4
5	1864	2.15	13	71	30	16.9	58.1	45.1
4	1152	2	43	78	11	39.3	70.1	17.2
3	919	1.92	64	66	15	62.5	69.3	25.3
2	776	1.82	14	54	14	15.4	69.6	20.5
1	449	1.44	36	36	54	36.7	42	58.6

and I find you have several FWE significant clusters



Again, sorry for the trouble.  With @TomMaullin’s help we’re on our way to integrating WB output into the SPM results interface.

-Tom

**Comment by nicholst** [comment]
@copelora: I’ve found the problem… SwE masks all output images implicitly with NaN, and FSL *hates* NaN’s :)

So if you do the following you’ll be all set:

fslmaths lP+ -nan lP+_nan
fslmaths lP_FWE- -nan lP_FWE-_nan
fslmaths lP_clusterFWE+ -nan lP_clusterFWE+_nan

… and then cluster will work:

$FSLDIR/bin/cluster -i lP_clusterFWE+_nan -t $(echo "-l(0.05)/l(10)"|bc -l)
Cluster Index	Voxels	MAX	MAX X (vox)	MAX Y (vox)	MAX Z (vox)	COG X (vox)	COG Y (vox)	COG Z (vox)
6	15522	3	14	34	9	39.1	22.6	28.4
5	1864	2.15	13	71	30	16.9	58.1	45.1
4	1152	2	43	78	11	39.3	70.1	17.2
3	919	1.92	64	66	15	62.5	69.3	25.3
2	776	1.82	14	54	14	15.4	69.6	20.5
1	449	1.44	36	36	54	36.7	42	58.6

and I find you have several FWE significant clusters
![image](https://user-images.githubusercontent.com/5155907/40768480-541d1d48-64ad-11e8-889b-f858b44bc728.png)



Again, sorry for the trouble.  With @TomMaullin’s help we’re on our way to integrating WB output into the SPM results interface.

-Tom

**Comment by copelora** [comment]
@nicholst: We're getting funny results when following the fslmaths approach. Basically, all the coordinates are positive (including what you pasted above). Perhaps we're not interpreting them the right way? I'll attach the results in both list and image form, as well as the files used to create them, on OxFile.

**Comment by nicholst** [comment]
Sorry! My bad. You need to use the `--mm` option with cluster. Then you should get millimeter and not voxel coordinates

**Comment by copelora** [comment]
I've noticed that the value of the maximum intensity within a cluster seems to have an upper limit of 3. Has anyone found this to be the case?

**Comment by BryanGuillaume** [comment]
The upper limit of 3 is due to the number of wild bootstraps you have probably used. Per default, it is set to 999 bootstraps, which yields a minimum obtainable p-value of 1 / (999 + 1) = 0.001 (note that the + 1 is needed to account for the original statistics). In the -log10-scale, we get -log10(0.001) = 3, which is in turn the largest  -log10(p-value) obtainable. To increase this, you can simply increase the number of bootstraps. For example, setting it to 9999 will yield a minimum reachable p-value of 1/(9999 + 1) = 0.0001 and maximum -log10(p-value) of -log10(0.0001) = 4.

**Comment by nicholst** [comment]
I think we can close this once #23 & #24 are merged and released

**Comment by TomMaullin** [comment]
This issue has been addressed in PR #23. Information is now available through the SPM display window.
