### ISSUE TITLE
New release 1.2.10

### ISSUE THREAD

**Issue by TomMaullin** [NISOx-BDI/SwE-toolbox#51]
As it has been a month since our last release, and there have been some major changes to the code, as well as some rectified bugs, I thought perhaps it would be best to make a new release before we add TFCE to the code. What are your thoughts on this @nicholst ?

**Comment by nicholst** [comment]
I would like to minimise the number of releases, e.g. no more than once a month.

To that end, what about releasing *after* we add TFCE?  Or are you worried that's going to take some time?

**Comment by TomMaullin** [comment]
I believe TFCE should be done within a few working days so I guess a new release can wait until then. The only reason I suggested making one before hand is it would make it much easier to trace any errors users find which were caused by changes to the code made before TFCE. As TFCE is quite a big update my logic was to isolate it as much as possible from other changes to the code so that if a bug is found we know instantly that the TFCE update was the cause.

I am happy to make a release after the TFCE update however.

**Comment by nicholst** [comment]
I see the concern, but I think we're OK.  What are all the changes?  I
tried comparing master to v1.2.9 and it's up to date.

**Comment by TomMaullin** [comment]
The most notable changes are:

 - Small volume corrections (#47)
 - GUI update (#46)
 - Allowing multiple covariates to be specified (#45)
 - The addition of the `swe_update.m` code (#42)

These should not be in version 1.2.9 I believe.

**Comment by nicholst** [comment]
Thank you!  Keep me posted on TFCE.

**Comment by TomMaullin** [comment]
Version 1.2.10 has been released with small bug fixes but none of the updates contained in the master branch currently.
