### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#52]
Update help so that...

1. Download page http://www.nisox.org/Software/SwE/download points you to 'man' for installation instructions

2. Manual page http://www.nisox.org/Software/SwE/man should tell you to unzip the SwE-toolbox into the spm12/toolboxes directory, and then start with "swe" command.

**Comment by TomMaullin** [comment]
This has now been resolved by [PR 63 on the NISOx-BDI repository.](https://github.com/NISOx-BDI/NISOx-BDI.github.io/pull/63)
