### ISSUE TITLE
Provide descriptions of .mat files

### ISSUE THREAD

**Issue by jonkoller** [NISOx-BDI/SwE-toolbox#6]
Provide descriptions of:

minScore.mat
maxScore.mat
maxClusterSize.mat
maxClusterSizeNeg.mat

It looks like the first value in the vector is from the data, and the rest are the permutations, is that right?

**Comment by nicholst** [comment]
Good suggestion @jonkoller.  BTW, you have correctly guessed the interpretation of these files; to be precise, the elements (2:end) are corresponding extremal statistics for each _bootstrap_ sample.

**Comment by TomMaullin** [comment]
This issue has been addressed by providing full documentation on the NISOx website [here](http://www.nisox.org/Software/SwE/).
