### ISSUE TITLE
Check for incompatibility when loading SwE.mat

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#69]
Not sure if this is feasible, but it would be really nice if we check for version incompatibilities when loading up the SwE.mat... at least issuing a warning if the major version number differs.

**Comment by TomMaullin** [comment]
I'm not sure if we could do this for previous version numbers but we could from now on include the version number somewhere inside the `SwE.mat` and then we can do a check against that?

**Comment by nicholst** [comment]
Indeed. As a baby step, let’s at least make sure the full version number is recorded in SwE.mat for 2.0.0. Check any SPM.mat you might have to see if they save it by chance.

**Comment by TomMaullin** [comment]
This has been resolved by PR #88
