### ISSUE TITLE
WB results clean up

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#8]
WB analyses leave a large number of files, in particular `YfittedWB_XXXX.{img,hdr}` and `ResWB_XXXX.{img,hdr}`.  They don't appear to be recycled or used otherwise if you do a subsequent WB run.

Should they instead be deleted after a run?

**Comment by TomMaullin** [comment]
This issue has been resolved following PRs #9 , #12 and #19
