### ISSUE TITLE
Description of WB equivalent z/x stat image only refer's to z

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#80]
@TomMaullin - Am I right that on this line
https://github.com/NISOx-BDI/SwE-toolbox/blob/master/swe_cp_WB.m#L624

```matlab
'Z score image for wild bootstrap voxelwise results.'
```
should actually be set adaptively depending on whether `eSTAT` is `z` or `x`?

**Comment by TomMaullin** [comment]
Apologies, this has now been resolved on the `TFCE` branch.

**Comment by TomMaullin** [comment]
This issue has now been addressed by PR #48
